### ISSUE TITLE
Bad regular expressions

### ISSUE THREAD

**Issue by M-Porter** [clessg/atom-expand-selection-to-quotes#11]
The regular expression on [line 30](https://github.com/clessg/atom-expand-selection-to-quotes/blob/master/lib/expand-selection-to-quotes.coffee#L30) is wrong. That regular expression is checking for `|`. I think what you want is just ``/[`'"]/g``. The brackets mean match any character in set and unless you meant to capture `|` then it is incorrect.

**Comment by clessg** [comment]
Thanks!
