### ISSUE TITLE
Not working with Atom 1.4.0

### ISSUE THREAD

**Issue by brunogenaro** [clessg/atom-expand-selection-to-quotes#8]
Hello,

I've installed this package and tried the CMD-' and didn't work. 
I've also added this on my personal keymap.cson:

``` 'atom-text-editor':
  "cmd-'": 'expand-selection-to-quotes:toggle'
```

And still not working.

I don't have other packages installed, it's a fresh brand-new Atom installation.

**Comment by kek** [comment]
Works for me in Atom 1.7.2. What does it say if press `Cmd-.` first to toggle the keybinding resolver display?

**Comment by clessg** [comment]
I believe this is fixed now. If not, I'll re-open this issue. Thanks!
